### ISSUE TITLE
NoSuchElementException in tomcat for example bot

### ISSUE THREAD

**Issue by ThePianoDentist** [lightbringer/dota2ai#2]
As I am not experienced with java web-stuff (and in-general), if the solution was relatively obvious was hoping might see it. I followed instructions as closely as I could

I get an internal server error when the add-on tries to start the bot
"POST /Dota2BotFramework/api/service/select HTTP/1.1" 500

(In example the request, and request in lua config is /Dota2AIService/... however using this just got me 404's with the tomcat instructions)

I do have:
E:\Program Files (x86)\apachetomcat\apache-tomcat-8.5.5\webapps\Dota2BotFramework\WEB-INF\lib\Bot.jar 

The Bot.jar created from doing mvn package(from inside intellij) on the ExampleBot pom.xml
that is the only file I have added to the Dota2BotFramework folder after 'deploying' the war file with the tomcat manager

Googling the issue I mainly just got glassfish jersey bug reports, however NoSuchElementException suggests that I have left something out somewhere.

(exception is occurring on lines
`final ServiceLoader<Bot> botLoader = ServiceLoader.load( Bot.class );
        bot = botLoader.iterator().next();`
indicating there are no Bot.class to be loaded, therefore next() excepts. is the Bot.class it is trying to load the one in the /WEB-INF/lib/Bot.jar?
)

Full catalina exception attached
[catalinaexec.txt](https://github.com/lightbringer/dota2ai/files/483792/catalinaexec.txt)

**Comment by lightbringer** [comment]
I hope this info helps you locating the issue:
The ServiceLoader mechanism is something that Orcacle introduced with Java 6. It allows a class to request an instance of  another class that implements a particular interface (Bot.class) without actually knowing the actual implementing class (Lina.class). The line you quoted above is the part where the webservice part request an instance of a bot from the JVM. NoSuchElement simply states that the framework has not found a class in the classpath that implements the Bot.class interface.

However, how does the ServiceLoader knows where and which class implements the requested interface? The long description is at http://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html , but I'll give you the relevant part here: the Bot.jar (a JAR is just a zip file you can open with any archiver) should contain a file META-INF/services/se.lu.lucs.dota2.framework.bot.Bot with a single line in.
The name of the file indicates which interface is implemented and must not be changed, the line **within** the file specifies which is the actual Bot class. In the example "de.lighti.dota2.bot.Lina". If you renamed the class or write your own, you have to change that.

That's the most obvious issue that comes to my mind. Maybe the intellij maven integration didn't grab the services file from the source tree?

**Comment by ThePianoDentist** [comment]
Woohoo!

it was missing out the file in intellij maven builds, mvn straight from command line, eclipse, everything
My issue was

...\dota2ai\Example Bot\src\main\ **webapp** \META-INF\services
needed renaming to
...\dota2ai\Example Bot\src\main\ **resources** \META-INF\services

and then it just works
thanks for help tracking down issue
 :)

**Comment by lightbringer** [comment]
Glad I could help. I underestimated though how many people would like to use the Java code, so I'm working on a much simpler solution.
