### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by DmitryTyshlangov** [lightbringer/dota2ai#3]
Example bot lina can only level up ability. It does not move or attack, just idle. 

in log
SEVERE: Could not send response to the client
java.net.SocketException: Socket closed

In class Dota2AIService variable 

private final static String CONTENT_TYPE = "content/type";

should have value "content-type" i think.

**Comment by lightbringer** [comment]
Yeah, that does definitely look like a typo.

**Comment by lightbringer** [comment]
Mind also that the example Lina doesn't do anything until you type "lina go" in team chat.
