### ISSUE TITLE
CreateHTTPRequest always return nil

### ISSUE THREAD

**Issue by hpduy17** [lightbringer/dota2ai#5]
I try to run your project but client cannot send http request to server. The reason has been shown in Vconsole : 
[ W VScript              ]: Script Runtime Error: scripts/vscripts/events.lua:167: attempt to call global 'CreateHTTPRequest' (a nil value)

**Comment by lightbringer** [comment]
I think it has something to do with the changes they made internally to the HTTP call. At least that's what this thread http://dev.dota2.com/showthread.php?t=278464 suggests. I'll look into it.

**Comment by lightbringer** [comment]
I just ran the example bot without a problem after committing this fix. So I suppose it's solved. Let me know if you run into other troubles.
